# Generated by Django 5.0 on 2023-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        ("manpower", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mp_list",
            index=models.Index(fields=["id"], name="manpower_mp_id_2d0470_idx"),
        ),
        migrations.AddIndex(
            model_name="mp_list",
            index=models.Index(
                fields=["first_name"], name="manpower_mp_first_n_09b7f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mp_list",
            index=models.Index(
                fields=["last_name"], name="manpower_mp_last_na_58e710_idx"
            ),
        ),
    ]
