# Generated by Django 5.0 on 2023-12-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "gov",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("area", models.IntegerField(blank=True, null=True)),
                ("population", models.IntegerField(blank=True, null=True)),
                ("main_city", models.CharField(blank=True, max_length=50, null=True)),
                ("cities", models.IntegerField(blank=True, null=True)),
                ("centers", models.IntegerField(blank=True, null=True)),
                ("neighborhoods", models.IntegerField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("discription", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
