# Generated by Django 5.0 on 2023-12-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="client_name_test",
            fields=[
                (
                    "client_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("client_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="project_name_test",
            name="client_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tests.client_name_test"
            ),
        ),
    ]
