# Generated by Django 5.0 on 2023-12-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0002_client_name_test_alter_project_name_test_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_name_test",
            name="client_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
