# Generated by Django 5.0 on 2023-12-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0004_alter_project_name_test_options_mp_location_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mp_location_test",
            name="id",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
