# Generated by Django 5.0 on 2023-12-18 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0005_alter_mp_location_test_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eqp_list_test",
            fields=[
                (
                    "equn",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxValueValidator(99999999)],
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("capacity", models.CharField(max_length=50)),
                ("project", models.CharField(max_length=50)),
                ("sap", models.CharField(max_length=50)),
                ("recipient", models.CharField(max_length=8)),
                ("date", models.DateField()),
                ("kpi", models.FloatField()),
                ("efficiency", models.FloatField()),
                ("fail", models.IntegerField()),
                ("work", models.IntegerField()),
                ("rate", models.IntegerField()),
                ("dep", models.IntegerField()),
                ("note", models.TextField()),
            ],
        ),
    ]
