# Generated by Django 5.0 on 2023-12-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0006_eqp_list_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eqp_list_test",
            name="dep",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="eqp_list_test",
            name="efficiency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eqp_list_test",
            name="fail",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eqp_list_test",
            name="kpi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eqp_list_test",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eqp_list_test",
            name="rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eqp_list_test",
            name="work",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
